import VennTopology

-- Large, input-specific computations remain explicit native-decision dependencies.
#print axioms Venn17.Topology.realized_surface_verified
#print axioms Venn17.Topology.diagram_triangulation_counts_verified
#print axioms Venn17.Topology.diagramFiniteTriangulation
#print axioms Venn17.Topology.diagram_classification_input_verified
#print axioms Venn17.Topology.diagramPolygonalHomeomorph
#print axioms Venn17.Topology.diagramCanonicalHomeomorph
#print axioms Venn17.Topology.diagram_classification_and_euler_verified
#print axioms Venn17.Topology.PolygonVertices.diagram_polygon_euler_lower_bound
#print axioms Venn17.Topology.diagramSphereHomeomorphOfEulerPreserved
#print axioms Venn17.Topology.realized_arrangement_verified
#print axioms Venn17.Topology.punctured_arrangement_verified
#print axioms Venn17.Topology.diagram_rotation_curve_image
#print axioms Venn17.Topology.diagram_rotation_region_image
#print axioms Venn17.Topology.diagramRegion_punctured_pathConnected
#print axioms Venn17.Topology.diagram_transverse_crossing
#print axioms Venn17.Topology.punctured_transverse_crossing
#print axioms Venn17.Topology.diagram_bit_field_verified
#print axioms Venn17.Topology.diagram_sides_verified
#print axioms Venn17.Topology.diagramRegion_eq_sides
#print axioms Venn17.Topology.puncturedSide_pathConnected
#print axioms Venn17.Topology.punctured_curve_complement_component_count
#print axioms Venn17.Topology.puncturedRegion_eq_sides
#print axioms Venn17.Topology.planeSide_true_bounded
#print axioms Venn17.Topology.planeSide_false_unbounded
#print axioms Venn17.Topology.plane_curve_complement_component_count
#print axioms Venn17.Topology.planar_sides_verified
-- These generic geometric arguments require only Lean's standard logical axioms.
#print axioms Venn17.Topology.PolygonVertices.eulerCharacteristic_signedIso
#print axioms Venn17.Topology.PolygonVertices.geometric_vertex_count_le
#print axioms Venn17.Topology.PolygonVertices.orientable_euler_characteristic
#print axioms Venn17.Topology.PolygonVertices.nonOrientable_euler_characteristic
#print axioms Venn17.Topology.PolygonVertices.sphere_euler_characteristic
#print axioms Venn17.Topology.PolygonVertices.normalForm_eq_sphere_of_euler_ge_two
#print axioms Venn17.Topology.geometricEdgeOccurrenceEquiv
#print axioms Venn17.Topology.PresentationClosedness.normalizationEquivalent_iff
#print axioms Venn17.Topology.PresentationClosedness.closed_classification
#print axioms LeanEval.Topology.ClassificationOfSurfaces.FiniteCyclicPresentation.hasEvalRepresentative
#print axioms Venn17.Topology.Coordinates.FiniteCoordinates.homeomorph
#print axioms Venn17.Topology.finiteCellFaceEquiv
#print axioms Venn17.Topology.encoded_edge_valence_eq_two
#print axioms Venn17.Topology.strongVertexStarConnected_of_links
#print axioms Venn17.Topology.dart_endpoints_injective
#print axioms Venn17.Topology.triangle_pair_dart
#print axioms Venn17.Topology.directedEdge_card
#print axioms Venn17.Topology.encoded_vertex_count
#print axioms Venn17.Topology.encoded_edge_count
#print axioms Venn17.Topology.encoded_triangle_count
#print axioms Venn17.Topology.encodedGeometricFaceEquiv
#print axioms Venn17.Topology.geometric_no_higher_faces
#print axioms Venn17.Topology.CrossingSquare.homeomorph
#print axioms Venn17.Topology.Quad.centerSquareChart
#print axioms Venn17.Topology.Quad.centerSquareChart_even_axis
#print axioms Venn17.Topology.bitSign_flip
#print axioms Venn17.Topology.preconnected_diff_singleton_of_neighborhood
#print axioms Venn17.Topology.all_bit_patterns
#print axioms Venn17.Topology.Quad.faceSign_cases
#print axioms Venn17.Topology.Quad.bitField_continuous
#print axioms Venn17.Topology.Quad.bitField_triangle
#print axioms Venn17.Topology.Coordinates.punctured_region_pathConnected
#print axioms Venn17.Topology.Quad.Automorphism.edgeCurve_image
#print axioms Venn17.Topology.Coordinates.circlePolygonHomeomorph
#print axioms Venn17.Topology.Coordinates.pairPolygonHomeomorph
#print axioms Venn17.Topology.Coordinates.openStarDiskHomeomorph
#print axioms Venn17.Topology.planar_jordan_separation
#print axioms Venn17.Topology.planar_jordan_separation_circle

-- Normalization Euler invariance and the unconditional planar realization.
#print axioms Venn17.Topology.PolygonVertices.eulerCharacteristic_unorientedIso
#print axioms Venn17.Topology.PolygonVertices.expandVertexEquiv
#print axioms Venn17.Topology.PolygonVertices.splitVertexEquiv
#print axioms Venn17.Topology.PolygonVertices.eulerCharacteristic_normalForm
#print axioms Venn17.Topology.diagram_normal_form_eq_sphere
#print axioms Venn17.Topology.diagramSphereHomeomorph
#print axioms Venn17.Topology.diagram_polygon_vertex_count
#print axioms Venn17.Topology.sphereWithoutPointHomeomorph
#print axioms Venn17.Topology.diagramPlaneHomeomorph
#print axioms Venn17.Topology.planar_venn_diagram_verified
#print axioms Venn17.Topology.planar_no_triple_intersections
#print axioms Venn17.Topology.planar_crossing_iff
#print axioms Venn17.Topology.planar_transverse_crossing
#print axioms Venn17.Topology.planar_symmetry_period
#print axioms Venn17.Topology.planar_symmetry_no_short_period
#print axioms Venn17.Topology.planar_symmetry_curve_image
#print axioms Venn17.Topology.planar_symmetry_region_image
#print axioms Venn17.Topology.planar_symmetry_fixed_iff
#print axioms Venn17.Topology.planar_symmetry_unique_fixed_point

-- Free cyclic covering and actual local rigid-rotation conjugacies.
#print axioms Venn17.Topology.minimalPeriod_eq_prime_of_not_fixed
#print axioms Venn17.Topology.rotationOrbitProjection_isCoveringMap
#print axioms Venn17.Topology.rotationOrbitProjection_fiber_card
#print axioms Venn17.Topology.Coordinates.labeledPolygonHomeomorph_rotation
#print axioms Venn17.Topology.Coordinates.linkConeDiskHomeomorph_rotation
#print axioms Venn17.Topology.supplied_pole_link_action_verified
#print axioms Venn17.Topology.zero_pole_link_rotation
#print axioms Venn17.Topology.one_pole_link_rotation
#print axioms Venn17.Topology.poleDiskDiagram_continuous
#print axioms Venn17.Topology.poleDiskDiagram_injective
#print axioms Venn17.Topology.poleDiskDiagram_zero
#print axioms Venn17.Topology.diagram_pole_disk_conjugacy
#print axioms Venn17.Topology.pole_disk_range_mem_nhds

-- Explicit equivariant meridians and their Jordan boundaries.
#print axioms Venn17.Topology.meridian_labels_verified
#print axioms Venn17.Topology.meridian_triangles_verified
#print axioms Venn17.Topology.Coordinates.simplex_inter_subset_vertex
#print axioms Venn17.Topology.diagramMeridianHomeomorph
#print axioms Venn17.Topology.diagramMeridianMap_zero
#print axioms Venn17.Topology.diagramMeridianMap_one
#print axioms Venn17.Topology.diagram_meridians_inter
#print axioms Venn17.Topology.diagram_meridian_boundary_eq_union
#print axioms Venn17.Topology.diagram_meridian_system

-- Checked closed sectors, full Schoenflies, and boundary-preserving disk charts.
#print axioms Schoenflies.schoenflies
#print axioms Schoenflies.MoiseChapter9.hasMoiseInsideDiskExtension
#print axioms Venn17.Topology.sector_colors_verified
#print axioms Venn17.Topology.sector_corners_verified
#print axioms Venn17.Topology.sector_overlaps_verified
#print axioms Venn17.Topology.sector_boundary_verified
#print axioms Venn17.Topology.sector_dual_verified
#print axioms Venn17.Topology.sector_connected_verified
#print axioms Venn17.Topology.sector_face_counts_verified
#print axioms Venn17.Topology.diagram_sectors_cover
#print axioms Venn17.Topology.diagramSector_compact
#print axioms Venn17.Topology.diagramSector_pathConnected
#print axioms Venn17.Topology.diagram_sector_rotation
#print axioms Venn17.Topology.sector_inter_subset_boundary
#print axioms Venn17.Topology.sector_frontier_subset
#print axioms Venn17.Topology.compactJordanRegionHomeomorph
#print axioms Venn17.Topology.puncturedJordanDisk_boundary
#print axioms Venn17.Topology.sectorDiskHomeomorph
#print axioms Venn17.Topology.sectorDiskHomeomorph_boundary
#print axioms Venn17.Topology.diagram_sectors_are_closed_disks
#print axioms Venn17.Topology.equivariantSectorDisk_boundary
#print axioms Venn17.Topology.equivariantSectorDisk_rotation
#print axioms Venn17.Topology.axialRotationMap_isometry
#print axioms Venn17.Topology.rigidSphereRotation_period
#print axioms Venn17.Topology.rigidDirection_injective
#print axioms Venn17.Topology.sphereMeridianBoundary_injective
#print axioms Venn17.Topology.sphereLuneDisk
#print axioms Venn17.Topology.sphereLuneDisk_boundary
#print axioms Venn17.Topology.rigidSectorDisk_boundary
#print axioms Venn17.Topology.equivariantRigidSectorDisk_boundary
#print axioms Venn17.Topology.equivariantRigidSectorDisk_rotation
#print axioms Venn17.Topology.rigid_sectors_cover
#print axioms Venn17.Topology.rigid_sector_inter_subset_boundary
#print axioms Venn17.Topology.sectorConjugacy_boundary
#print axioms Venn17.Topology.sectorConjugacy_rotation
#print axioms Venn17.Topology.sectorwise_rigid_conjugacy
#print axioms Venn17.Topology.sphere_conjugacy_of_boundary_compatibility
#print axioms Venn17.Topology.diagramMeridianBoundaryMap_front
#print axioms Venn17.Topology.diagramMeridianBoundaryMap_back
#print axioms Venn17.Topology.meridian_parameter_compatibility
#print axioms Venn17.Topology.sector_boundary_compatibility
#print axioms Venn17.Topology.rigidSphereConjugacy
#print axioms Venn17.Topology.rigidSphereConjugacy_rotation
#print axioms Venn17.Topology.rigidSphereConjugacy_zero
#print axioms Venn17.Topology.rigidSphereConjugacy_one
#print axioms Venn17.Topology.northStereographicComplex_rotation
#print axioms Venn17.Topology.rigidPlaneHomeomorph_rotation
#print axioms Venn17.Topology.rigidPlaneRotation_complex
#print axioms Venn17.Topology.planeSymmetryConjugacy_rotation
#print axioms Venn17.Topology.rigidPlane_membership_verified
#print axioms Venn17.Topology.rigidPlaneRotation_period
#print axioms Venn17.Topology.rigidPlaneRotation_no_short_period
#print axioms Venn17.Topology.rigidPlane_no_triple
#print axioms Venn17.Topology.rigidPlane_crossing_iff
#print axioms Venn17.Topology.rigidPlane_transverse_crossing
#print axioms Venn17.Topology.rotationalVenn_rotation
#print axioms Venn17.Topology.supplied_simple_rotational_venn
#print axioms Venn17.Topology.exists_simple_rotational_venn_17
