#!/usr/bin/env python3
"""Find disjoint rotation meridians; Lean independently checks the output."""
import collections
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
raw = json.loads((ROOT / 'venn17-local-c3-s2.json').read_text())
graph, face_witnesses = collections.defaultdict(set), {}
for fi, face in enumerate(raw['faces']):
    vs = sorted(int(s[::-1], 2) for s in face)
    u = vs[0]
    a, b = sorted(x ^ u for x in vs[1:] if (x ^ u) & ((x ^ u) - 1) == 0)
    cycle = [u, u ^ a, u ^ a ^ b, u ^ b]
    for x, y in zip(cycle, cycle[1:] + cycle[:1]):
        graph[x].add(y)
        graph[y].add(x)
        face_witnesses[min(x, y), max(x, y)] = fi
rotate = lambda x: (x >> 1) | ((x & 1) << 16)
reps = {}
for x in graph:
    if x in reps:
        continue
    orbit = [x]
    for _ in range(16):
        orbit.append(rotate(orbit[-1]))
    for y in orbit:
        reps[y] = min(orbit)
todo, previous, lift = [0], {0: None}, {0: 0}
for r in todo:
    if r == 131071:
        break
    for y in sorted(graph[lift[r]]):
        s = reps[y]
        if s not in previous:
            previous[s], lift[s] = r, y
            todo.append(s)
r, path = 131071, []
while r is not None:
    path.append(lift[r])
    r = previous[r]
path.reverse()
assert len(path) == 18
rows, p = [], path
for _ in range(17):
    rows.append([face_witnesses[min(x, y), max(x, y)] for x, y in zip(p, p[1:])])
    p = [rotate(x) for x in p]
assert p == path
report = {'path': path, 'faces': rows}
(ROOT / 'output/meridian-certificate.json').write_text(json.dumps(report, indent=2) + '\n')
array = lambda xs: '#[' + ', '.join(map(str, xs)) + ']'
source = '''import VennCore.Rotation

/-! Generated by scripts/find_meridians.py. All data are checked independently
in MeridianCertificate.lean; the search program is outside the trust boundary. -/
namespace Venn17.Topology

def meridianSeed : Array Nat := %s

def meridianFaceRows : Array (Array Nat) := #[
%s]

end Venn17.Topology
''' % (array(path), ',\n'.join('  ' + array(row) for row in rows))
(ROOT / 'VennTopology/MeridianData.lean').write_text(source)
print('Found 17 rotated meridians, each with 17 edges.')
