#!/usr/bin/env python3
"""Propose sectors cut along the proved meridians; Lean checks the used data."""
import json,collections
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
raw=json.loads((ROOT / 'venn19-closure-s196002.json').read_text())
faces=[]; edges=collections.defaultdict(list)
for fi,face in enumerate(raw['faces']):
 v=sorted(int(x[::-1],2) for x in face);u=v[0];a,b=sorted(x^u for x in v[1:] if(x^u)&((x^u)-1)==0);f=[u,u^a,u^a^b,u^b];faces.append(f)
 for x,y in zip(f,f[1:]+f[:1]):edges[min(x,y),max(x,y)].append(fi)
p=json.loads((ROOT / 'output/meridian-certificate.json').read_text())['path'];rot=lambda x:(x>>1)|((x&1)<<18)
cut={};paths=[]
for k in range(19):
 paths.append(p)
 for x,y in zip(p,p[1:]):cut[min(x,y),max(x,y)]=k
 p=list(map(rot,p))
adj=collections.defaultdict(list)
for e,fs in edges.items():
 if e not in cut:
  f,g=fs;adj[f].append(g);adj[g].append(f)
colors={};comps=[]
for f in range(len(faces)):
 if f in colors:continue
 k=len(comps);q=[f];colors[f]=k
 for g in q:
  for h in adj[g]:
   if h not in colors:colors[h]=k;q.append(h)
 comps.append(q)
sector_numbers = {}
report = []
for k,fs in enumerate(comps):
 es=collections.Counter(tuple(sorted((x,y))) for f in fs for x,y in zip(faces[f],faces[f][1:]+faces[f][:1])); vs={v for f in fs for v in faces[f]};bd=[e for e,count in es.items() if count==1]
 boundary_arcs = {cut[e] for e in bd}
 sector = next(i for i in range(19) if boundary_arcs == {i,(i+1)%19})
 sector_numbers[k] = sector
 report.append(dict(sector=sector, vertices=len(vs), edges=len(es), faces=len(fs),
                    euler=len(vs)-len(es)+len(fs), boundary_edges=len(bd)))

face_colors = [sector_numbers[colors[f]] for f in range(len(faces))]
boundary_faces = []
for k in range(19):
    cycle = paths[k] + list(reversed(paths[(k+1)%19][1:-1]))
    row = []
    for x,y in zip(cycle,cycle[1:]+cycle[:1]):
        row.append(next(f for f in edges[min(x,y),max(x,y)] if face_colors[f] == k))
    boundary_faces.append(row)
array = lambda xs: '#[' + ', '.join(map(str, xs)) + ']'
source = '''import VennTopology.MeridianCertificate

/-! Generated by scripts/find_sectors.py. These are proposed face colors and
boundary face witnesses, independently checked in SectorCertificate.lean. -/
namespace Venn19.Topology

def suppliedSectorColors : Array Nat :=
  "%s".toList.toArray.map (fun c => c.toNat - 65)

def sectorBoundaryFaces : Array (Array Nat) := #[
%s]

end Venn19.Topology
''' % (''.join(chr(65+k) for k in face_colors), ',\n'.join('  '+array(row) for row in boundary_faces))
(ROOT / 'VennTopology/SectorData.lean').write_text(source)
(ROOT / 'output/sector-certificate.json').write_text(json.dumps(sorted(report,key=lambda r:r['sector']),indent=2)+'\n')
print('Proposed 19 sectors, 27594 quadrilaterals and 38 boundary edges each.')
